export default {
  heading: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#696969',
    marginLeft: '5%',
    marginBottom: '1%',
    marginTop: '2%',
    textTransform: 'capitalize',
  },
  flightName:{
    fontWeight: 'bold',
    fontsize: 20,
    color: 'black',
    marginLeft: '15%',
    marginBottom: 10,
    marginTop: '2%',
  },
  iconStyle: {
    fontSize: 40,
    marginTop: 10,
    marginLeft: 10,
    color: 'black',
  },
  swap: {},
  smalliconStyle: {
    fontSize: 30,
    marginTop: 10,
    marginLeft: 50,
    color: 'black',
  },
  details: {
    alignItems: 'center',
    marginLeft: 40,
    paddingTop: 20,
    fontSize: 24,
    fontWeight: 'bold',
    color: 'black',
  },

  subtitle: {
    color: 'gray',
    fontSize: 10,
    marginLeft: '21%',
    marginBottom: '1%',
  },
  Flightname: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'gray',
    marginTop: '2%',
  },
  Date: {
    marginLeft: '1%',
    fontSize: 15,
    color: 'gray',
    marginTop: '2%',
  },
  moreinfo: {
    color: '#696969',
  },

  subCardView: {
    height: '100%',
    width: '70%',
    borderRadius: 10,
    backgroundColor: '#DCDCDC',
    borderColor: 'black',
    borderWidth: 2,
    borderStyle: 'solid',
    marginLeft: '15%',

    alignItems: 'center',
  },
  flightdate:{
    fontWeight: 'bold',
    fontsize: 22,
    color: 'black',
    marginLeft: '4%',
    marginBottom: 10,
    marginTop: '2%',
  },
  aircraftType:{
    fontWeight: 'bold',
    fontsize: 20,
    color: 'black',
    marginLeft: '15%',
    marginBottom: 10,
    marginTop: '2%',
  },
  tail:{
    fontWeight: 'bold',
    fontsize: 20,
    color: 'black',
    marginLeft: '15%',
    marginBottom: 10,
    marginTop: '2%',
  },
  flightAttendant:{
    fontWeight: 'bold',
    color: 'black',
    marginLeft: '20%',
    marginBottom: 10,
  },
  captain_officer:{
    fontWeight: 'bold',
    color: 'black',
    marginLeft: '20%',
  },
};
